### ISSUE TITLE
如何使用 指定的IP地址访问 不是127.0.0.1

### ISSUE THREAD

**Issue by bluemoon37** [cooolr/chatgpt-proxy-web#10]

**Comment by cooolr** [comment]
config.py listen_url改成指定ip不行吗？

**Comment by bluemoon37** [comment]
solved
# 如果更改了此属性，需要手动删除资源目录 [If you change this property, the `resource` directory needs to be manually deleted.]
listen_url = "http://127.0.0.1"
listen_port = 8011
