### ISSUE TITLE
直接用ip:端口访问，报这个错

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#11]
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "main.py", line 170, in index
    r = requests.request(request.method, url, headers=headers, cookies=cookie_dict, data=request.data, proxies=proxies)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='chat.openai.com', port=443): Max retries exceeded with url: /chat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
`

**Comment by cooolr** [comment]
看着像是你本地requests库ssl相关的错误，puid都填了吧

**Comment by ludashi2020** [comment]
> 看着像是你本地requests库ssl相关的错误，puid都填了吧

都填写了。plus订阅，我用是服务器ip:端口访问。没有使用域名和ssl证书这些。

**Comment by cooolr** [comment]
这个错误是程序去请求chat.openai.com的时候报错，你服务器没装ssl吧，装一下看看

**Comment by ludashi2020** [comment]
> 这个错误是程序去请求chat.openai.com的时候报错，你服务器没装ssl吧，装一下看看
> 
> ```shell
> sudo apt-get install openssl libssl-dev
> sudo apt-get install python3-openssl
> ```

我是用的centos7,安装试试

**Comment by ludashi2020** [comment]
可以了，但是现在报这个错误。![WeChat截图_20230309160731.png](https://pic.shenbian.tv/2023/03/09/94f38467ca8df.png)

**Comment by cooolr** [comment]
不可能，绝对不可能，现在官网抽风了，我的也不行了。

**Comment by cooolr** [comment]
我的已经恢复了，看你这个报错就像是你的ip被拒绝了，你在命令行curl一下看有没有报错
```bash
curl chat.openai.com
```

**Comment by cooolr** [comment]
> [root@dbci ~]# curl chat.openai.com error code: 1020[root@dbci ~]#

你看你看，你的ip被拒绝了，不过还有得救，就是套warp，https://cooolr.notion.site/chatgpt-warp-90500a66153c4e97938abe4ba3808b9a

到第七步不用配置warp，把warp注册的代理加到config.py，proxies里面就好了，socks5://127.0.0.1:40000

**Comment by cooolr** [comment]
看起来你的服务器是独立ip的啊，怎么会被拒绝

**Comment by ludashi2020** [comment]
> 看起来你的服务器是独立ip的啊，怎么会被拒绝
session-token是不是cooike里
__Secure-next-auth.session-token=后面的内容呢？

**Comment by cooolr** [comment]
> > 看起来你的服务器是独立ip的啊，怎么会被拒绝
> > session-token是不是cooike里
> > __Secure-next-auth.session-token=后面的内容呢？

是的，最好是在开发者模式->应用->cookie那里复制

**Comment by ludashi2020** [comment]
> > > 看起来你的服务器是独立ip的啊，怎么会被拒绝
> > > session-token是不是cooike里
> > > __Secure-next-auth.session-token=后面的内容呢？
> 
> 是的，最好是在开发者模式->应用->cookie那里复制

现在网页打开，但是出现这个问题。![图片_20230309180311.png](https://pic.shenbian.tv/2023/03/09/69b7d9ad4e02e.png)

**Comment by ludashi2020** [comment]
> > > 看起来你的服务器是独立ip的啊，怎么会被拒绝
> > > session-token是不是cooike里
> > > __Secure-next-auth.session-token=后面的内容呢？
> 
> 是的，最好是在开发者模式->应用->cookie那里复制

现在网页打开，但是出现这个问题。![图片_20230309180311.png](https://pic.shenbian.tv/2023/03/09/69b7d9ad4e02e.png)

**Comment by cooolr** [comment]
这个问题是由于你变更了listen_url又没有删除resource目录导致的，昨晚我调整了代码，重新拉取重来吧 。

**Comment by cooolr** [comment]
没有反馈，关闭issue
