### ISSUE TITLE
使用Plus账号登陆后，左侧仍然显示普通用户，且对话会提示错误

### ISSUE THREAD

**Issue by crosys** [cooolr/chatgpt-proxy-web#12]
对话时提示错误如下：
An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com.

**Comment by cooolr** [comment]
确认以下内容:
1. 是否添加_puid参数
2. lsiten_url和访问url是否一致

**Comment by cooolr** [comment]
Upgrade to Plus的选项我也不知道啥原因，问题不大。
我现在自己用就是用nginx加https啊，参考我的，listen_url写域名就好了，nginx那里proxy_pass指向127.0.0.1:8012

listen_url = "https://cooolr.online"
listen_port = 8012

**Comment by ludashi2020** [comment]
> proxy_pass

我试过这样设置了，但是访问地址会显示https://cooolr.online:8012/

**Comment by cooolr** [comment]
> > proxy_pass
> 
> 我试过这样设置了，但是访问地址会显示https://cooolr.online:8012/

就是这部分逻辑，我处理的还有问题，今晚再看一下

**Comment by cooolr** [comment]
修复了

**Comment by cooolr** [comment]
> > Upgrade to Plus的选项我也不知道啥原因，问题不大。 我现在自己用就是用nginx加https啊，参考我的，listen_url写域名就好了，nginx那里proxy_pass指向127.0.0.1:8012
> > listen_url = "https://cooolr.online" listen_port = 8012
> 
> 这个时候能正常对话的地址是[https://cooolr.online就好，还是仍然要需要加端口号？](https://cooolr.online%E5%B0%B1%E5%A5%BD%EF%BC%8C%E8%BF%98%E6%98%AF%E4%BB%8D%E7%84%B6%E8%A6%81%E9%9C%80%E8%A6%81%E5%8A%A0%E7%AB%AF%E5%8F%A3%E5%8F%B7%EF%BC%9F) 想让https走指定端口号那可就折腾了。。。。

不需要加端口号，需要nginx proxy_pass
