### ISSUE TITLE
登录后，这个地方一直在转圈圈

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#14]
![WeChat截图_20230310114632.png](https://pic.shenbian.tv/2023/03/10/b883fa4459b16.png)

**Comment by cooolr** [comment]
f12网络栏看看有什么错误

**Comment by ludashi2020** [comment]
f12网络栏看了都是200状态，没有报错。![WeChat截图_20230310115235.png](https://pic.shenbian.tv/2023/03/10/91d2c97ca4d04.png)

**Comment by cooolr** [comment]
这种通常是你的代理或者服务器访问chatgpt慢的原因。

**Comment by ludashi2020** [comment]
> 这种通常是你的代理或者服务器访问chatgpt慢的原因。

我目前用的是新加坡的云服务器，哪里的机器访问chatgpt更快呢？

**Comment by dogfight360** [comment]
一样情况.相同IP下直接登陆正常使用.反代就转圈
状态码是200.但请求/api/auth/session返回了{"details":"Rate limit exceeded"}
尝试更换puid无果
使用的是账户密码方式登陆,plus账户

**Comment by dogfight360** [comment]
> 一样情况.相同IP下直接登陆正常使用.反代就转圈 状态码是200.但请求/api/auth/session返回了{"details":"Rate limit exceeded"} 尝试更换puid无果 使用的是账户密码方式登陆,plus账户

同一个cookie访问频率似乎限制的很低.静置后目前恢复正常了

**Comment by cooolr** [comment]
目前openai限制和封禁比较严格，用warp代理几乎被秒封，多用户同时使用也会被封，但是这个封是假封，换一个puid就好了，目前使用风险较大，请谨慎使用。
![Snipaste_2023-03-14_17-09-51](https://user-images.githubusercontent.com/32413353/224952139-454e0e42-ded8-4630-a9b7-c5c6042d058d.png)

**Comment by cooolr** [comment]
issue关闭。
