### ISSUE TITLE
这种是怎么实现的？普通号也能登录，不要plus订阅

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#16]
![QQ截图20230315184843.png](https://pic.shenbian.tv/2023/03/15/74872e4c02638.png)
https://ink.cn.com/

登录进去之后，还能看到历史会话记录。

**Comment by cooolr** [comment]
这种应该也是某种漏洞，我这个项目也可以啊，只要有pui d可以带n个免费账号

**Comment by chuanhhoang** [comment]
Could I use _puid with different free accounts?

**Comment by cooolr** [comment]
> Could I use _puid with different free accounts?

yes, you can!

**Comment by cooolr** [comment]
关闭issue
