### ISSUE TITLE
借朋友的puid登录进去，没有历史会话记录，回答问题报错。

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#17]
![WeChat截图_20230315193559.png](https://pic.shenbian.tv/2023/03/15/4b1709072f5b3.png)
使用的是邮箱密码方式登录

**Comment by cooolr** [comment]
这种情况一般都是你的listen_url和访问URL不对应的原因，检查一下

**Comment by ludashi2020** [comment]
listen_url和访问URL都是同一个，其他配置信息不变，朋友用他的邮箱密码填进去就能用，换我的邮箱密码就回答报错。

**Comment by cooolr** [comment]
> listen_url和访问URL都是同一个，其他配置信息不变，朋友用他的邮箱密码填进去就能用，换我的邮箱密码就回答报错。

要按f12进入开发者模式网络栏，他肯定会有报错，看看报错报的是什么错？

**Comment by ludashi2020** [comment]
我的是报internet server error，他的是200状态，没有错误。puid是他的，我借用，使用普通号登录就这样了。

**Comment by ludashi2020** [comment]
怎么开dug模式？没看到错误日志生成

**Comment by cooolr** [comment]
你在官网能登录你的账号吗，这种情况要么就是你账号被封了，我需要更多的错误提示以及截图，比如具体哪个请求报500？命令行界面没有错误，输出吗？不应该

**Comment by ludashi2020** [comment]
明天早上我试试有没有详细的报错信息，再发上来。目测服务端报错。

**Comment by ludashi2020** [comment]
这是我的普通账号登录，借用了朋友的puid
![WeChat截图_20230316110017.png](https://pic.shenbian.tv/2023/03/16/056262868fad3.png)
提问的时候，报错了，会话历史也不显示
![WeChat截图_20230316110251.png](https://pic.shenbian.tv/2023/03/16/2957762220008.png)
此时服务器后台日志是这样的
![WeChat截图_20230316110413.png](https://pic.shenbian.tv/2023/03/16/42d787566275a.png)
这个链接https://我的域名/backend-api/accounts/check)状态码还是200
![WeChat截图_20230316110657.png](https://pic.shenbian.tv/2023/03/16/08df2c21ff321.png)
但是返回的却是Internal Server Error
![WeChat截图_20230316110657.png](https://pic.shenbian.tv/2023/03/16/08df2c21ff321.png)
这个路径/backend-api/conversations?offset=0&limit=20也是200状态，但是返回也是Internal Server Error
![WeChat截图_20230316111024.png](https://pic.shenbian.tv/2023/03/16/4aef0140fc55d.png)
后台仍然是这样的，没有看到报错日志
![WeChat截图_20230316111228.png](https://pic.shenbian.tv/2023/03/16/11a6932fe6ab7.png)

**Comment by ludashi2020** [comment]
补充说明一点，我的账号没有被封，可以正常登录官网操作。
![chatgpt.png](https://pic.shenbian.tv/2023/03/16/dc760ffe14a69.png)

**Comment by cooolr** [comment]
这看不出什么问题，奇怪，你可以在你本地127.0.0.1运行看看，实在不行就算了，我发现这个项目有时候页面也会出错，不稳定。可以尝试这个项目 https://github.com/Chanzhaoyu/chatgpt-web

**Comment by ludashi2020** [comment]
> 

你的可以普通话使用puid登录正常使用吗？如果可以那就是跟puid有关了

**Comment by ludashi2020** [comment]
我好像找到原因了，普通账户借用puid登录进去，F12那里看不到cookie信息，Fiddler抓包也是没有cookie信息的
![WeChat截图_20230316192102.png](https://pic.shenbian.tv/2023/03/16/e9a5464f98392.png)
这是抓包
![WeChat截图_20230316192237.png](https://pic.shenbian.tv/2023/03/16/34730b2b58109.png)
是不是服务端程序的问题呢？

**Comment by cooolr** [comment]
你试一下在本地127能不能成功先

**Comment by ludashi2020** [comment]
> 你试一下在本地127能不能成功先

好的

**Comment by ludashi2020** [comment]
> > 你试一下在本地127能不能成功先
> 
> 好的

本地测试了，结果一模一样。
![WeChat截图_20230317105348.png](https://pic.shenbian.tv/2023/03/17/9b83365cd9fa5.png)
![WeChat截图_20230317110154.png](https://pic.shenbian.tv/2023/03/17/66eaf9f658fc0.png)

应该是服务端的问题。

**Comment by cooolr** [comment]
我更新了代码config部分，重新下拉配置看看，另外看报错像是puid失效。&nbsp;


cooolr
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月17日(星期五) 中午11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cooolr/chatgpt-proxy-web] 借朋友的puid登录进去，没有历史会话记录，回答问题报错。 (Issue #17)





   
你试一下在本地127能不能成功先
  
好的
  
本地测试了，结果一模一样。
 
 
 
应该是服务端的问题。

**Comment by ludashi2020** [comment]
> 

好的，我重新拉取代码部署试试

**Comment by ludashi2020** [comment]
> 我更新了代码config部分，重新下拉配置看看，另外看报错像是puid失效。&nbsp; cooolr ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月17日(星期五) 中午11:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [cooolr/chatgpt-proxy-web] 借朋友的puid登录进去，没有历史会话记录，回答问题报错。 (Issue #17) 你试一下在本地127能不能成功先 好的 本地测试了，结果一模一样。 应该是服务端的问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

难道付费订阅的puid不能用于普通免费账户？

**Comment by cooolr** [comment]
能的，但是puid有时候会失效，实在不行换一个账号吧

**Comment by ludashi2020** [comment]
> 能的，但是puid有时候会失效，实在不行换一个账号吧 Message ID: ***@***.***&gt;

重新拉取代码部署，结果一模一样,能登录但是没有会话记录，回答问题报错。用不了别人的puid

**Comment by cooolr** [comment]
我试了几次都没问题

**Comment by cooolr** [comment]
解决不了，issue关闭
