### ISSUE TITLE
新获取的puid已经不能绕过cf了

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#19]
貌似官方已经修复了漏洞？
新获取的puid已经不能绕过cf了
会提示这个
This web property is not accessible via this address

**Comment by cooolr** [comment]
应该是

**Comment by ludashi2020** [comment]
这个问题https://github.com/cooolr/chatgpt-proxy-web/issues/17能解决吗？

**Comment by ludashi2020** [comment]
我的现在彻底不能用了，报这个错误了
This web property is not accessible via this address

**Comment by ludashi2020** [comment]
换一个puid又复活了，真的奇怪

**Comment by gtgc2005** [comment]
应该还没有修复，我是下午新付费的plus，刚刚试了下可以正常绕过
