### ISSUE TITLE
讨论贴

### ISSUE THREAD

**Issue by cooolr** [cooolr/chatgpt-proxy-web#2]
没有_puid真的搞不定

**Comment by shenfe** [comment]
你好，请教个可能很简单的问题：什么情况会遇到cloudflare的问题？为什么反向代理就能解决这个问题？

**Comment by cooolr** [comment]
@shenfe 免费账号会遇到cloudflare的问题，反向代理不能能解决这个问题，是plus账号的_puid参数能解决这个问题。

**Comment by shenfe** [comment]
> @shenfe 免费账号会遇到cloudflare的问题，反向代理不能能解决这个问题，是plus账号的_puid参数能解决这个问题。

谢谢回答：）
如果已经是plus账号，是否可以直接http client调用了（设好必要的cookie和header），不会有cloudflare的限制？

**Comment by cooolr** [comment]
> 

是的。

**Comment by shenfe** [comment]
> > 
> 
> 是的。

谢谢解答

**Comment by orwithout** [comment]
ChatGPTUnofficialProxyAPI

**Comment by cooolr** [comment]
@orwithout  ChatGPTUnofficialProxyAPI的原理我也知道，但是这个项目我主要是自己带朋友们用的，没动力搞个接口。

**Comment by cooolr** [comment]
> 有这样的api ?: ChatGPTUnofficialProxyAPI
> 
> 参考： https://github.com/Chanzhaoyu/chatgpt-web [Chanzhaoyu/chatgpt-web#138](https://github.com/Chanzhaoyu/chatgpt-web/issues/138)

要不我也搞个接口，兼容一下我这个项目？

**Comment by ludashi2020** [comment]
> > 有这样的api ?: ChatGPTUnofficialProxyAPI
> > 参考： https://github.com/Chanzhaoyu/chatgpt-web [Chanzhaoyu/chatgpt-web#138](https://github.com/Chanzhaoyu/chatgpt-web/issues/138)
> 
> 要不我也搞个接口，兼容一下我这个项目？

搞一个绕过cloudflare的api代理接口

**Comment by cooolr** [comment]
> > > 有这样的api ?: ChatGPTUnofficialProxyAPI
> > > 参考： https://github.com/Chanzhaoyu/chatgpt-web [Chanzhaoyu/chatgpt-web#138](https://github.com/Chanzhaoyu/chatgpt-web/issues/138)
> > 
> > 
> > 要不我也搞个接口，兼容一下我这个项目？
> 
> 搞一个绕过cloudflare的api代理接口

但是这种接口多多少少都有点违规的，就怕用的人多，牵连大家一锅端了，这几天openAI开始严查违规行为了。

**Comment by orwithout** [comment]
现在用api都要小心了🙇，真是……
api弄出来不就是给人用于批量任务么。

我觉得可以考虑搞个这种：弄个聊天界面（比如说一个telegram群），里面拉个chatgpt聊天机器人
一个run_on_linux机器人（这个机器人运行在一台Linux机器上，它会实时监控群聊天，从里面抓取代码、然后在Linux机器里去执行）

我这几天在到处实验聊天软件，想找一个无法被封禁的聊天软件、或者能自己部署服务器的

体验了一二十款，发现：
element聊天、
status聊天、
spike.im、
simplex聊天、
Berty聊天
都很值得关注

另外发现微软的产品基本都没有被封禁的？那么它家的skype、team、甚至office365在线文档也值得关注

（在线文档的共享编辑功能感觉其实很强大？可以作为聊天功能来用也睡不到…）

**Comment by orwithout** [comment]
一个聊天软件能被封禁：
1、iphone、安装商店上下架app；对于安卓则还需封禁app的web上的下载连接
2、封服务器IP地址、端口、域名
3、对于可以自己假设服务器、并能改变服务通信端口的一些开源的聊天软件，则嗅探IP数据包特征、路由或防火墙上直接把数据包丢弃…

所以对于一个聊天软件，即便是基于去中心化（无中心服务器）的、p2p的、可以自己私密部署服务器的通讯软件……也是可以通过识别它的通讯协议的ip数据包特征来进行屏蔽。

综合考虑，电子邮箱通讯是最难被封禁的：因为显然防火墙不能直接封禁电子邮箱协议、因为这个东西太通用了；2电子邮箱服务器可以自己随便搭建；

所以spike.im真的很特别…
而如果面向web3的聊天软件Berty聊天能与email协议结合，就完美了
