### ISSUE TITLE
看看这个forks项目，貌似修复了普通账号借用puid的问题。

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#21]
https://github.com/shr-go/chatgpt-proxy-web
貌似修复了bug，我试过一次，普通账号借用puid显示历史会话记录，已经回答问题不报错了。

**Comment by cooolr** [comment]
奇怪

**Comment by ludashi2020** [comment]
> 奇怪

我看他的修改记录显示优化了puid的设置流程以及修复了部分bug
