### ISSUE TITLE
请问这个puid怎么获得呀？cookie选项里没有呀

### ISSUE THREAD

**Issue by ChengChong001** [cooolr/chatgpt-proxy-web#22]

**Comment by cooolr** [comment]
这个参数是plus会员的cookie才有的，如果没有，可以问朋友要一个，我可以提供一个
user-81UIaesx4cLmhC9pVd8N0yxD:1679472646-eQ%2FZc9kqsjcUPEPT%2FmsXboT2GlPwjzQ5qPxC5xIrx28%3D


这个项目定期提供共享plus账号，可以登录账号进去拿puid参数https://github.com/lovezm/chatgpt-plus-freeshare

**Comment by ChengChong001** [comment]
感谢回复，是plus会员，但是没有这个选项，能提问但是看不到历史记录，估计是我的vpn有问题了。

**Comment by cooolr** [comment]
这两天官网抽风，我上官网也看不到历史

**Comment by ChengChong001** [comment]
请问如果想开启网页的账号密码认证，相关的账号密码应该如何设置呢？

**Comment by cooolr** [comment]
config.py里面说得很清楚了啊，如果你使用chatgpt邮箱密码的话，就是用chatgpt邮箱密码登录，如果使用session-token的话，就要自定义一个邮箱密码，生成md5码填到`user`选项，也有示例。

**Comment by ChengChong001** [comment]
# Enable account and password authentication for the webpage.
is_verify = False

我指的是这个字段，意思应该是可以开启这个页面的访问认证吧？设置为true之后的账号密码如何设置呢？

**Comment by cooolr** [comment]
设置成True, 设置为true之后的账号密码如何设置，我上一条回复的就是这个问题的答案。
