### ISSUE TITLE
很早之前fokrs的项目偶然间可用使用任意官网账号登录

### ISSUE THREAD

**Issue by ludashi2020** [cooolr/chatgpt-proxy-web#23]
`https://github.com/shr-go/chatgpt-proxy-web`
试过了免费账号和收费账号，都能登录进去，还能显示历史会话记录以及正常回复，但是现在更新后就不行了，不知道为什么。
![QQ截图20230323143406.png](https://pic.shenbian.tv/2023/03/23/bd6096075640b.png)
![QQ截图20230323143517.png](https://pic.shenbian.tv/2023/03/23/0490858311ee9.png)

**Comment by cooolr** [comment]
你说的是克隆的那个项目吗，试试我的项目

**Comment by ludashi2020** [comment]
> 你说的是克隆的那个项目吗，试试我的项目

他就是克隆你的项目。你的项目以及现在他更新后的项目都不行了。登录进去不能看到历史会话记录。只能用puid原始账号进去使用。

**Comment by cooolr** [comment]
我的正常啊
&nbsp;


cooolr
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月23日(星期四) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cooolr/chatgpt-proxy-web] 很早之前fokrs的项目偶然间可用使用任意官网账号登录 (Issue #23)





  
你说的是克隆的那个项目吗，试试我的项目
  
他就是克隆你的项目。你的项目以及现在他更新后的项目都不行了。登录进去不能看到历史会话记录。只能用puid原始账号进去使用。

**Comment by ludashi2020** [comment]
> 你说的是克隆的那个项目吗，试试我的项目

你的项目，我调试了几十次，无一例外都是失败。只能用原始puid账号进去

**Comment by ludashi2020** [comment]
> 我的正常啊 &nbsp; cooolr ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月23日(星期四) 下午2:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [cooolr/chatgpt-proxy-web] 很早之前fokrs的项目偶然间可用使用任意官网账号登录 (Issue #23) 你说的是克隆的那个项目吗，试试我的项目 他就是克隆你的项目。你的项目以及现在他更新后的项目都不行了。登录进去不能看到历史会话记录。只能用puid原始账号进去使用。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你试试任意免费官网账号进去看看？这个https://user.openai.yt任意免费官网账号都能进去。不需要任何后台设置

**Comment by ludashi2020** [comment]
我的plus号也能进去,还显示历史会话记录
![QQ截图20230323144420.png](https://pic.shenbian.tv/2023/03/23/6cbdf907237bf.png)

**Comment by cooolr** [comment]
你发的那个链接确实登进去正常，我的项目刚试了一下卡住了，不知道什么原因。

**Comment by ludashi2020** [comment]
> 你发的那个链接确实登进去正常，我的项目刚试了一下卡住了，不知道什么原因。

我也不知道什么原因，百思不得其解，关键还拿不到错误日志，总是显示200

**Comment by ludashi2020** [comment]
> 你发的那个链接确实登进去正常，我的项目刚试了一下卡住了，不知道什么原因。

我也不知道什么原因，百思不得其解，关键还拿不到错误日志，总是显示200
