### ISSUE TITLE
NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by bluemoon37** [cooolr/chatgpt-proxy-web#6]
NetworkError when attempting to fetch resource.

**Comment by cooolr** [comment]
Did you fill in the puid parameter?

**Comment by bluemoon37** [comment]
> puid

有puid parameter
chrome 里 找的 
我是 plus

**Comment by cooolr** [comment]
> > puid
> 
> 有puid parameter chrome 里 找的 我是 plus

你应该有用代理吧，f12看看报啥错，如果登录成功后，应该不会有问题才对，我早上调整了一下项目，你可以重新拉

**Comment by bluemoon37** [comment]
{"detail":"Sentry dropped data due to a quota or internal rate limit being reached. This will not affect your application. See https://docs.sentry.io/product/accounts/quotas/ for more information."}

**Comment by cooolr** [comment]
> {"detail":"Sentry dropped data due to a quota or internal rate limit being reached. This will not affect your application. See https://docs.sentry.io/product/accounts/quotas/ for more information."}

这个错误不影响使用啊，是上报日志的错误

**Comment by bluemoon37** [comment]
脚本无法获取响应主体（原因：CORS Missing Allow Origin）

**Comment by cooolr** [comment]
> 脚本无法获取响应主体（原因：CORS Missing Allow Origin） http://127.0.0.1:8011/backend-api/models

你浏览器访问的也是http://127.0.0.1:8011/ 吗，这没有跨域问题啊，我没有遇到过

**Comment by bluemoon37** [comment]
可以访问了http://127.0.0.1:8011/

**Comment by bluemoon37** [comment]
访问http://127.0.0.1:8011/ 解决了
